services:
  youtube_queuer:
    container_name: youtube_queuer
    env_file:
      - .env
    build:
      context: .
    networks:
      - fajita
    ports:
      - "7000:7000"
    restart: always

networks:
  fajita:
    driver: bridge
  container-dmz:
    external: true
